export enum PATIENT_PROFILE_STATUS {
  WAITING = "WAITING",
  IN_CONSULTATION = "IN CONSULTATION",
  WILL_BE_RETURNING = "WILL BE RETURNING",
  RESOLVED = "RESOLVED",
}

export enum PATIENT_PROFILE_TYPE {
  NORMAL = "NORMAL",
  RETURNING = "RETURNING",
}
