export enum PATIENT_STATUS {
  WAITING = "WAITING",
  IN_CONSULTATION = "IN CONSULTATION",
  WILL_BE_RETURNING = "WILL BE RETURNING",
  RESOLVED = "RESOLVED",
}

export enum PATIENT_TYPE {
  NORMAL = "NORMAL",
  RETURNING = "RETURNING",
}

export const PATIENT_POSITION_GAP = 1000;
