CREATE TABLE IF NOT EXISTS queue_details (
    id UUID PRIMARY KEY DEFAULT UUIDV7(),
    name TEXT NOT NULL,
    type SMALLINT NOT NULL DEFAULT 1 CHECK (type > 0),
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);