export enum QUEUE_TYPE {
  DOCTOR_QUEUE = "DOCTOR QUEUE",
  TESTING_QUEUE = "TESTING QUEUE",
  LAB_QUEUE = "LAB QUEUE",
}

export enum QUEUE_STATUS {
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  STOPPED = "STOPPED",
}
